services:
  # PostgreSQL service - Database
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin # Default user
      POSTGRES_PASSWORD: admin # Default password
      POSTGRES_DB: mydb # Database name
    ports:
      - "5432:5432" # Database connection port
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persistent storage
    networks:
      - postgres_network # Communication network between containers

  # pgAdmin service - Web interface to manage PostgreSQL
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com # Email to login
      PGADMIN_DEFAULT_PASSWORD: admin # Password to login
    ports:
      - "5050:80" # Port to access the web interface
    depends_on:
      - postgres
    networks:
      - postgres_network

volumes:
  postgres_data:

networks:
  postgres_network:
    driver: bridge
